[versions]
checkstyle = "12.3.0"
junit = "6.0.1"
mockito = "5.21.0"

[libraries]
assertj = { module = "org.assertj:assertj-core", version = "3.27.6" }
json-path = { module = "com.jayway.jsonpath:json-path", version = "2.10.0" }
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-runtime = { module = "org.junit.platform:junit-platform-launcher" }
logback = { module = "ch.qos.logback:logback-classic", version = "1.5.22" }
mockito-core = { module ="org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
opentest4j = { module = "org.opentest4j:opentest4j", version = "1.3.0" }
slf4j-api = { module = "org.slf4j:slf4j-api", version = "2.0.17" }

[plugins]
shipkit = { id = "org.shipkit.shipkit-auto-version", version = "2.1.2" }
